from __future__ import annotations

from typing import Any

_SIMPLE_TYPE_MAP: dict[str, str] = {
    # JSON-ish → WIT types
    "string": "string",
    "str": "string",
    "text": "string",
    "bool": "bool",
    "boolean": "bool",
    "int": "s64",
    "integer": "s64",
    "float": "float64",
    "number": "float64",
    "bytes": "list<u8>",
}


def _normalize_ident(name: str) -> str:
    """Normalize field and type identifiers to a WIT-friendly form.

    Very conservative: lowercase, replace spaces and hyphens with underscores,
    strip non-alnum/underscore characters, and ensure it starts with a letter.
    """
    import re

    s = name.strip().lower()
    s = re.sub(r"[\s\-]+", "_", s)
    s = re.sub(r"[^a-z0-9_]", "", s)
    if not s or s[0].isdigit():
        s = f"_{s}"
    return s


def _map_scalar(json_type: str | None) -> str:
    if not json_type:
        return "string"
    jt = json_type.strip().lower()
    return _SIMPLE_TYPE_MAP.get(jt, "string")


def _map_field(field: dict[str, Any]) -> tuple[str, str]:
    """Return (field_name, wit_type) for a single field spec.

    Supported shapes:
    - {"name": "text", "type": "string"}
    - {"name": "values", "type": "array", "items": {"type": "string"}}
    - {"name": "cfg", "type": "object", "properties": {"k": {"type": "string"}}}
    Fallback for unknowns → string.
    """
    name = _normalize_ident(field.get("name", "field"))
    ftype = field.get("type")

    if ftype is None:
        return name, "string"

    ftype_l = str(ftype).lower()

    if ftype_l in _SIMPLE_TYPE_MAP:
        return name, _map_scalar(ftype_l)

    if ftype_l in ("array", "list"):
        items = field.get("items") or {}
        inner = _map_scalar(items.get("type")) if isinstance(items, dict) else "string"
        return name, f"list<{inner}>"

    if ftype_l in ("object", "record", "map"):
        # If properties given, create an inline record; otherwise default to string map
        props = field.get("properties")
        if isinstance(props, dict) and props:
            # Flatten to a record of simple scalars when possible
            parts: list[str] = []
            for k, v in props.items():
                fname = _normalize_ident(k)
                fty = _map_scalar(v.get("type") if isinstance(v, dict) else None)
                parts.append(f"    {fname}: {fty},")
            return name, f"record {{\n{chr(10).join(parts)}\n}}"
        # Generic object → string via JSON text for M0
        return name, "string"

    # Unknown → string
    return name, "string"


def _emit_record(type_name: str, fields: list[dict[str, Any]]) -> str:
    if not fields:
        return f"type {type_name} = record {{}}\n"
    mapped = [_map_field(f) for f in fields]
    lines = [f"type {type_name} = record {{"]
    for key, wit_ty in mapped:
        lines.append(f"  {key}: {wit_ty},")
    lines.append("}\n")
    return "\n".join(lines)


def generate_wit(
    io_schema: dict[str, Any],
    *,
    world_name: str = "component",
    func_name: str = "process",
    input_type_name: str = "Input",
    output_type_name: str = "Output",
) -> str:
    """Generate a minimal WIT component interface from a Langflow I/O schema.

    The expected io_schema resembles:
        {
          "inputs": [{"name": "text", "type": "string"}],
          "outputs": [{"name": "text", "type": "string"}]
        }

    Returns a string containing a WIT world with a single exported function:
        export process: func(input: Input) -> Output
    with Input/Output records synthesized from the schema.

    This is intentionally minimal for M0 and favors practicality over
    completeness. Unknown/complex types degrade to string.
    """
    inputs = io_schema.get("inputs") or []
    outputs = io_schema.get("outputs") or []

    if not isinstance(inputs, list) or not isinstance(outputs, list):
        msg = "io_schema must contain 'inputs' and 'outputs' as lists"
        raise TypeError(msg)

    world_ident = _normalize_ident(world_name)
    func_ident = _normalize_ident(func_name)
    in_ty = _normalize_ident(input_type_name)
    out_ty = _normalize_ident(output_type_name)

    parts: list[str] = []
    parts.append("// Auto-generated by Langflow WIT generator (M0)\n")
    parts.append(_emit_record(in_ty, inputs))
    parts.append(_emit_record(out_ty, outputs))
    parts.append(f"world {world_ident} {{")
    parts.append(f"  export {func_ident}: func(input: {in_ty}) -> {out_ty}")
    parts.append("}\n")
    return "\n".join(parts)
